http:
  port : "8081"
  
sfdc:
  username : "fathimafarzi96@gmail.com"
  password : "John000@"
  token : "bBgBkiBGxcjHuzI60ctEp4FB"
  
file:
  accountsDir : "D:/FATHIMA FARZANA/study resources/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"